Aspnet Core Identity/ViewModels/Login.cs
using System.ComponentModel.DataAnnotations;

namespace Aspnet_Core_Identity.ViewModels
{
    public class Login
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public bool RememberMe { get; set; }
    }
}

Aspnet Core Identity/ViewModels/Register.cs
using System.ComponentModel.DataAnnotations;

namespace Aspnet_Core_Identity.ViewModels
{
    public class Register
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Compare(nameof(Password), ErrorMessage="Password and confirmation pass")]
        public string ConfirmPassword { get; set; }
    }
}

Aspnet Core Identity/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Aspnet_Core_Identity.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Aspnet Core Identity/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Aspnet_Core_Identity.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Aspnet Core Identity/Pages/Login.cshtml.cs
using Aspnet_Core_Identity.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace Aspnet_Core_Identity.Pages
{
    public class LoginModel : PageModel
    {
        public readonly SignInManager<IdentityUser> _signInManager;
        [BindProperty]
        public Login Model { get; set; }

        public LoginModel(SignInManager<IdentityUser> signInManager)
        {
            this._signInManager = signInManager;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            if (ModelState.IsValid)
            {
                var identityResult = await _signInManager.PasswordSignInAsync(Model.Email,Model.Password,Model.RememberMe,false);
                if (identityResult.Succeeded)
                {
                    if (returnUrl == null || returnUrl == "/")
                    {
                        return RedirectToPage("Privacy");
                    }
                    else return RedirectToPage(returnUrl);
                }

                ModelState.AddModelError("", "Username or Password is not correct");
            }
            return Page();
        }
    }
}

Aspnet Core Identity/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace Aspnet_Core_Identity.Pages
{
    public class LogoutModel : PageModel
    {
        public readonly SignInManager<IdentityUser> _signInManager;

        public LogoutModel(SignInManager<IdentityUser> signInManager)
        {
            this._signInManager = signInManager;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await _signInManager.SignOutAsync();

            return RedirectToPage("Login");
        }

        public  IActionResult OnPostDontLogoutAsync()
        {
            return RedirectToPage("Index");
        }
    }
}

Aspnet Core Identity/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Aspnet_Core_Identity.Pages
{
    [Authorize]
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Aspnet Core Identity/Pages/Register.cshtml.cs
using Aspnet_Core_Identity.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace Aspnet_Core_Identity.Pages
{
    public class RegisterModel : PageModel
    {
        private readonly UserManager<IdentityUser> _userManger;
        private readonly SignInManager<IdentityUser> _signInManager;

        [BindProperty]
        public Register Model { get; set; }
        public RegisterModel(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            this._userManger = userManager;
            this._signInManager= signInManager;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        { 
            if(ModelState.IsValid)
            {
                var user = new IdentityUser()
                {
                    UserName = Model.Email,
                    Email = Model.Email
                };
                var result = await _userManger.CreateAsync(user, Model.Password);
                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    return RedirectToPage("Index");
                }

                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
            }

            return Page();
        }
    }
}

Aspnet Core Identity/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Aspnet Core Identity/Pages/Login.cshtml
@page
@model Aspnet_Core_Identity.Pages.LoginModel
@{
}

<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Login</h1>

            <form method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="mb-3">
                    <div class="form-label" asp-for="Model.Email">Email Address</div>
                    <input type="email" asp-for="Model.Email" class="form-control" />
                    <span asp-validation-for="Model.Email" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <div class="form-label" asp-for="Model.Password">Password</div>
                    <input type="password" asp-for="Model.Password" class="form-control" />
                    <span asp-validation-for="Model.Password" class="text-danger"></span>
                </div>
                <div class="mb-3 form-check">                   
                    <input type="checkbox" asp-for="Model.RememberMe" class="form-check-input" />
                    <lable class="form-check-label" asp-for="Model.RememberMe">Remember Me?</lable>
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </form>
        </div>
    </div>
</div>

Aspnet Core Identity/Pages/Logout.cshtml
@page
@model Aspnet_Core_Identity.Pages.LogoutModel
@{
}

<form method="post">
    <div class="container mt-5"> 
    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <p>Are you sure wanna logout?></p>
            <p>
                <button class="btn btn-primary" asp-page-handler="Logout">Yes</button>
                <button class="btn btn-light ml-5 border-dark" asp-page-handler="DontLogout">Nope</button>
            </p>
        </div>
    </div>
</div>
</form>

Aspnet Core Identity/Pages/Register.cshtml
@page
@model Aspnet_Core_Identity.Pages.RegisterModel
@{
}

<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Register</h1>

            <form method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="mb-3">
                    <div class="form-label" asp-for="Model.Email">Email Address</div>
                    <input type="email" asp-for="Model.Email" class="form-control" />
                    <span asp-validation-for="Model.Email" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <div class="form-label" asp-for="Model.Password">Password</div>
                    <input type="password" asp-for="Model.Password" class="form-control" />
                    <span asp-validation-for="Model.Password" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <div class="form-label" asp-for="Model.ConfirmPassword">Confirm Password</div>
                    <input type="password" asp-for="Model.ConfirmPassword" class="form-control" />
                    <span asp-validation-for="Model.ConfirmPassword" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Register</button>
                </div>
            </form>
        </div>
    </div>
</div>

Aspnet Core Identity/Pages/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Aspnet_Core_Identity</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Aspnet_Core_Identity</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (SignInManager.IsSignedIn(User))
                        {
                                <ul class="navbar-nav flex-grow-1">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                                    </li>                                   

                                </ul>
                                <ul class="navbar-nav">
                                    <li class="nav-item">
                                        <a class="btn btn-primary"  asp-area="" asp-page="/Logout">Logout</a>
                                    </li>
                                </ul>
                        }
                        else
                        {
                                <ul class="navbar-nav d-flex justify-content-end flex-grow-1">
                                    <li class="nav-item">
                                        <a asp-page="/Login" class="btn btn-primary">Login</a>
                                    
                                    </li>
                                    <li class="nav-item">
                                        <a asp-page="/Register" class="btn btn-outline-secondary">Register</a>
                                    
                                    </li>
                                </ul>
                        }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Aspnet_Core_Identity - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>